# Generated by Django 2.1.7 on 2019-04-16 09:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mean',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mean_language', models.IntegerField(default=1)),
                ('mean_part', models.CharField(max_length=64)),
                ('mean_mean', models.TextField(max_length=16382)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_name', models.CharField(max_length=64, unique=True)),
                ('word_update_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('word_ph_en', models.CharField(max_length=64, null=True)),
                ('word_ph_am', models.CharField(max_length=64, null=True)),
                ('word_ph_en_mp3', models.BinaryField()),
                ('word_ph_am_mp3', models.BinaryField()),
            ],
        ),
        migrations.AddField(
            model_name='mean',
            name='mean_word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trans.Word'),
        ),
    ]
