# Generated by Django 2.1.7 on 2019-04-16 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trans', '0003_auto_20190416_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mean',
            name='mean_mean',
            field=models.TextField(max_length=65536),
        ),
    ]
